name: Build S23 Ultra Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Cache apt packages
      uses: actions/cache@v4
      with:
        path: /var/cache/apt/archives
        key: ${{ runner.os }}-apt-cache
        restore-keys: |
          ${{ runner.os }}-apt-cache

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git wget unzip build-essential device-tree-compiler lz4 xz-utils zlib1g-dev openjdk-17-jdk \
          gcc g++ python3 python-is-python3 p7zip-full android-sdk-libsparse-utils erofs-utils default-jdk gnupg flex \
          bison gperf zip curl libc6-dev libncurses-dev libx11-dev libreadline-dev libgl1 libgl1-mesa-dev python3-markdown \
          libxml2-utils xsltproc make repo cpio kmod openssl libelf-dev pahole libssl-dev libarchive-tools zstd --fix-missing && \
          wget http://security.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.3-2ubuntu0.1_amd64.deb && sudo dpkg -i libtinfo5_6.3-2ubuntu0.1_amd64.deb

    - name: Cache Clang toolchain
      uses: actions/cache@v4
      with:
        path: kernel_samsung_sm8550-common/clang
        key: clang-${{ runner.os }}-${{ github.run_id }}
        
    - name: Clone kernel source with submodules
      run: |
        git clone --recurse-submodules --shallow-submodules --depth=1 \
          https://github.com/samsung-sm8550/kernel_samsung_sm8550-common.git \
          -b ksunext-susfs/android13-5.15

    - name: Patch setup.sh
      run: |
        cd kernel_samsung_sm8550-common
        sed -i 's/next-susfs/next-susfs-dev/' KernelSU-Next/kernel/setup.sh

    - name: Download and run build script
      run: |
        cd kernel_samsung_sm8550-common
        wget https://raw.githubusercontent.com/DrRoot85/sukisupatch/refs/heads/main/build_ksu.sh
        chmod +x build_ksu.sh
        sed -i 's/make.*/make -j$(nproc)/' build_ksu.sh
        ./build_ksu.sh

    - name: Find and expose zip filename
      run: |
        cd kernel_samsung_sm8550-common
        ZIP_FILE=$(find . -name '*.zip' | head -n 1)
        echo "ZIP_FILE=$ZIP_FILE" >> $GITHUB_ENV

    - name: Upload ZIP as GitHub Actions artifact
      uses: actions/upload-artifact@v4
      with:
        name: s23ultra-kernel
        path: ${{ env.ZIP_FILE }}


    - name: Create GitHub Release and upload ZIP
      uses: softprops/action-gh-release@v1
      with:
        tag_name: s23ultra-${{ github.run_number }}
        name: S23 Series With KernelSU-Next & SUSFS v1.5.7
        body: |
          This release contains KernelSU-Next & SUSFS v1.5.7 & Magic Mount

          **KernelSU Next Last Dev Branch**

          Module:
          https://github.com/sidex15/ksu_module_susfs

          Non-Official Managers:
          https://github.com/KernelSU-Next/KernelSU-Next

          Features:
          [+] KernelSU-Next - Latest Dev Branch
          [+] SUSFS v1.5.7
          [+] Magic Mount Support
        files: ${{ env.ZIP_FILE }}
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
